baseURL = 'https://f5.com/'
languageCode = 'en-us'
title = 'F5 AppWorld 2026 Lab Guides'
enableGitInfo = true

[caches]
  [caches.modules]
    maxAge = -1

[module]
  [[module.imports]]
    path="github.com/nginxinc/nginx-hugo-theme"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    guessSyntax = true
    noClasses = false